export const HALLE = {
    BLOC_HUETTE_HAUPTHALLE: "BLOC_HUETTE_HAUPTHALLE",
    BLOC_HUETTE_AUSSENHALLE: "BLOC_HUETTE_AUSSENHALLE",
    BLOC_HUETTE_NEUEHALLE: "BLOC_HUETTE_NEUEHALLE",
} as const

export type Halle = keyof typeof HALLE
